### ISSUE TITLE
Only the first game is converted to NSP from 2-game XCI

### ISSUE THREAD

**Issue by jakaja** [dezem/SAK#10]
A game "Cat Quest + Cat Quest II Pawsome Pack" (https://www.nintendo.com/games/detail/cat-quest-plus-cat-quest-ii-pawsome-pack-switch/) has two games. When I insert the cartridge to Switch, two game icons appear to Launcher menu.

I dumped the cartridge with nxdumptool v1.1.10 as a XCI (dumping as a NSP only dumps the first game of two).
Dump filename is "Cat Quest v131072 (0100A2F006FBE000) + Cat Quest II v262144 (01008BE00E968000).xci"

When I use SAK v0.7.5 to convert this XCI (including 2 games) to NSP(s), the output is only the first game as NSP.
I expected both games would be handled and converted to separate NSPs.

I could provide the dumped XCI if needed for testing/fixing the issue.

**Comment by dezem** [comment]
Sorry I dont own these game.

But normaly on multicard games, it should convert it to different NSPs.
I tried it with Bioshock Remastered, so i get there three NSP files after that.

So i think the problem is the game itself?

What you can try:
With nxdumptool you can also dump it separate NSP files.
You should switch with L or R the game and redump it as NSP.
It only dumps the selected game as NSP.

**Comment by fandras32** [comment]
> A game "Cat Quest + Cat Quest II Pawsome Pack" (https://www.nintendo.com/games/detail/cat-quest-plus-cat-quest-ii-pawsome-pack-switch/) has two games. When I insert the cartridge to Switch, two game icons appear to Launcher menu.
> 
> I dumped the cartridge with nxdumptool v1.1.10 as a XCI (dumping as a NSP only dumps the first game of two).
> Dump filename is "Cat Quest v131072 (0100A2F006FBE000) + Cat Quest II v262144 (01008BE00E968000).xci"
> 
> When I use SAK v0.7.5 to convert this XCI (including 2 games) to NSP(s), the output is only the first game as NSP.
> I expected both games would be handled and converted to separate NSPs.
> 
> I could provide the dumped XCI if needed for testing/fixing the issue.

@jakaja can you write to me on email (cbool09@gmail.com)?
