### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by mczeus** [dezem/SAK#12]
hi,

ist es möglich das tool auch im Docker laufen zu lassen?
Dann bräuchte man nicht immer ein PC zur hand um mal files zu wandeln!
Vielleicht mit AtmoXL-Titel-Installer zusammen.

Grüße

**Comment by dezem** [comment]
Hi,
dürfte mit Win Server Core laufen. Nano bin ich mir nicht sicher.
Kannst dir ja gerne ein Container erstellen und austesten.

Von mir ist in der Richtung nichts geplant.

Gruß
kempa
