### ISSUE TITLE
Not Issue, just request - For Mac OS supported tool

### ISSUE THREAD

**Issue by Arthas91** [dezem/SAK#13]
Hi, any chance you are making a mac os supported SAK. I desperately need nsp to nsz compression. Running out of HD space. Thank you.

**Comment by dezem** [comment]
Hi, sorry i'm no mac os user.
SAK is Windows only.

But if you only want to compress nsp to nsz.
Take a look at:
https://github.com/nicoboss/nsz
https://github.com/julesontheroad/NSC_BUILDER/releases

It runs with python3, should work also on mac os
