### ISSUE TITLE
hacBrewPack missing DLLs on 0.7.8 releas

### ISSUE THREAD

**Issue by impeeza** [dezem/SAK#16]
Hi I just download Switch Army Knife (SAK) v0.7.8 release and try to generate a NSP forwarder for a NRO and get errors about msys-2.0.dll & msys-gcc_s-seh-1.dll missing files.

The hacBrewPack version 3.05 downloaded from github works fine without the dll files.  I did found the missing files on my c:\msys64\usr\bin\ folder, I think the compiled version of SAK is not linking external includes references.

**Comment by dezem** [comment]
Uh ya right, these are my own compiled binarys.
I replaced it with the latest release from hacbrewpack.

Thanks 👍
