### ISSUE TITLE
Forwarders do not allow video recording

### ISSUE THREAD

**Issue by impeeza** [dezem/SAK#17]
After creating a Forward for a NRO, and install it on the Swtich.  running the App works fine, but a blank Save Data of 64MB is created which is a space waste.  when the application is running pressing the capture button a picture is taken, but holding it a message «Unable to take a video capture now» is displayed.

I am using Atmosphère 0.19.3 and firmware 12.0.1

I think these are controlled by the file "nro_fw_control.nacp" but really do not know how to edit it.

thanks.

**Comment by impeeza** [comment]
If something help, the offset 0x3025 of nro_fw_control.nacp  file enable/disable savegame creation.
And offset 0x3035 control the Capture behavior 00: No Capture Allowed, 01: Screen Capture Allowed, 02: Video Capture Allowed

**Comment by dezem** [comment]
If you get a 64mb save file, so you dont use the latest SAK Version from 06.05.2021 from the releases.
There was a small update to fix that problem.

For the video capture, yes this setting is set to manual.

To easy edit the nacp file, you should use hacPackTools-NACP from The-4n.
You can extract it as xml, make your changes there.
And generate them back as ncap file 😉 
So you dont must search for Hex offsets...

At the next release of SAK.
I will include the options to enable the records option.

**Comment by impeeza** [comment]
🎉 super, thanks a lot. I will test it tomorrow.  Thanks a lot

**Comment by dezem** [comment]
Checkout my latest release 👍 
https://github.com/dezem/SAK/releases/tag/0.7.10
