### ISSUE TITLE
NSP to NSZ compression taking forever

### ISSUE THREAD

**Issue by G4merz** [dezem/SAK#19]
I waited for 1 hour and it didnt completed fast compression. Its a 10GB file, Overcooked All you can eat. Is that normal and i have to wait even more or its having some issue? Sorry for bad grammar (i think)

**Comment by G4merz** [comment]
also ill try to get the pc on at night to see if it really takes infinite time

**Comment by G4merz** [comment]
im really sorry, it just takes too much time. 2 hours to be exact. my apologies

**Comment by dezem** [comment]
Hi there,
yes compression of big files takes some time 😉 

You can also use batch compression for multiple nsp files.
Simple select multiple nsp files which you want to compress as nsz.
