### ISSUE TITLE
Webroot SecureAnywhere sees 4nxci.exe as a trojan.

### ISSUE THREAD

**Issue by nanashi89** [dezem/SAK#2]
After unzipping the compressed folder, Webroot SecureAnywhere, a computer protection program gave me the following message I included in this image file. It then proceeded to delete 4nxci.exe.

Why?
![Screenshot 2020-01-10 21 22 27](https://user-images.githubusercontent.com/23020427/72197479-baa81780-33ef-11ea-888c-11d873598792.png)

**Comment by dezem** [comment]
This is a false positiv message, you can ignore it.

Take a look at the link below, for other virus detections for the 4nxci.exe.
Webroot is the only one how detects it.

https://www.virustotal.com/gui/file/96f74e791710c2d5bd4f6eade9c9d11ef51c9c7df15f17e571d23c4b35185d6e/detection

**Comment by nanashi89** [comment]
OK, so how do I keep Webroot from deleting it? Is there some kind of "Exceptions" option I can use?

**Comment by nanashi89** [comment]
Mystery solved. https://docs.webroot.com/us/en/home/wsa_pc_userguide/Content/ManagingQuarantine/BlockingOrAllowingFiles.htm
Thanks anyway!
