### ISSUE TITLE
Illegal licensing (Where is the source code?)

### ISSUE THREAD

**Issue by xf1424** [dezem/SAK#21]
This project uses GPL-2 licensed programs and appears to be proprietary itself. This is illegal.

**Comment by dezem** [comment]
Nice try and short answer NO! 
SAK will remain closed source, its my work.

SAK is only a gui for the binary commandline tools which are included in the bin dir.
So i have nothing to worry about that 😉

If i include the tools or source code directly in SAK so yes. I must provide the source Code. 
But the GPL tools are in the bin folder. So nothing to complain...
