### ISSUE TITLE
NSZ compression options

### ISSUE THREAD

**Issue by HattDroid** [dezem/SAK#23]
Hi,

Could you please let know what are the option used for each level of NSZ compression in SAK?

I am compressing my nsp on another machine manually with the original nsz tool (https://github.com/nicoboss/nsz) but can't achieve the same file sizes as with SAK set on hard.

Thanks!

**Comment by dezem** [comment]
The compression uses NSC Builder and not the NSZ Tool from nicoboss.
So maybe its differrent
