### ISSUE TITLE
NSPs created with SAK are not working on Atmosphère 0.19.5

### ISSUE THREAD

**Issue by LeyendaV** [dezem/SAK#24]
Tested out on HOS 12.0.3

**Comment by dezem** [comment]
Only specific game or all your games dont work?

**Comment by dezem** [comment]
If all games dont work, you have a problem with your running CFW.
Probably bad AMS setup, missing / false sig patches or bad dumps please check it.

For help please go to a support forum or discord.

Its no problem of SAK itself. So i close the issue here...

Greez

**Comment by LeyendaV** [comment]
Looks like SAK has outdated components. 

Just tried https://github.com/StarDustCFW/SimpleNSPForwader and works perfectly, just letting you know.

**Comment by dezem** [comment]
Youre initial asking about problems with games created as NSP and now give me a link to an NSP forwarder creator?
These are two different things...

The used nx-hbloader is the latest version, maybe i need to recompile with latest libnx.

**Comment by dezem** [comment]
small notice nx-hbloader is updated with SAK 0.7.12
