### ISSUE TITLE
Converting back from compressed format results in a different hash

### ISSUE THREAD

**Issue by SamRohod** [dezem/SAK#28]
Hello,
I'm not in anyway knowledgeable about the switch game/DLC/update formats (.xci & .nsp & .xcz & .nsz). I just found it to be strange that compressing a game from  .xci-->.xcz  then decompressing it back  .xcz-->.xci  results in an MD5 different from the original. The same thing happens with .nsp & .nsz files.

My understanding is that .xcz files are just compressed .xci files and .nsz files are just compressed .nsp files.

What has changed in the files? Can the original state with the correct MD5 be retrieved in any way?

I ask this because I try to preserve my game collection matching No-intro dat with the smallest size possible.

Thanks

**Comment by dezem** [comment]
Hello,
no its not possible to decompress to the original hash.

I use NSC Builder to compress/decompress xci/xcz/nsp/nsz files with SAK.

Its normal if you modify it, that the hash changes. 

Its no problem for your backups 😉

**Comment by SamRohod** [comment]
It seems that NSZ recently added this:

https://github.com/nicoboss/nsz/pull/131
