### ISSUE TITLE
Disable "Return main menu" button while file explorer window is open

### ISSUE THREAD

**Issue by Signum21** [dezem/SAK#29]
If you press the "Return main menu" button multiple times while the file explorer window is open it will cause the program to close and open the main menu window multiple times after closing the file explorer window

Video: https://imgur.com/a/IkR85cT

**Comment by dezem** [comment]
Thx for reporting the issue. 
I will fix it with the next Release

**Comment by dezem** [comment]
Fixed with https://github.com/dezem/SAK/commit/1b4a6b790e4f2f0329f075991a56d25ed3d782b5

Check new release -> https://github.com/dezem/SAK/releases/tag/0.7.14
