### ISSUE TITLE
Progress Bar (not really an issue, just a recommendation)

### ISSUE THREAD

**Issue by Bonethugs1980** [dezem/SAK#3]
Could we get a progress bar with time stated progress etc.

Would be good to see how long a conversion or NSP+NSP update would take.

**Comment by dezem** [comment]
Hi @Bonethugs1980 
that's currently not possible.

All included tools you find at the bin folder, are called with CMD calls by SAK.
And these tools don't give me the current progress stats at STDOUT.

**Comment by Bonethugs1980** [comment]
Ah, OK.  I get you.  Thanks for replying, as mentioned not really an issue.

Will close this.
