### ISSUE TITLE
Problem with 13.2.0

### ISSUE THREAD

**Issue by Manolits** [dezem/SAK#31]
First of all thank you for your work. I never had a problem in the past with your program. I'm on sx os. New games on 13.2.0 like Asterix and record of Lodos war seem to start but stay on an infinite loop in the first loading screen before entering the game. Any ideas how to fix this?

**Comment by dezem** [comment]
Hi there,
you're saying you are on SX OS, then you stuck on FW11.0...

Patching games to lower firm doesn't work for all games.
Some new games need features from the new firmware, which causes the black screen or freeze.

The only solution is, to say goodbye to SX OS and switch to Atmosphere.
