### ISSUE TITLE
Bitdefender Sees SAK.exe as Nymeria.002

### ISSUE THREAD

**Issue by Bonethugs1980** [dezem/SAK#4]
Have you seen any other reports of this noted in title.

I did see a comment about false positive but seen as malware, not virus.

Is this still safe?  Bitdefender appeared to notice after one it's definitions updates...

**Comment by dezem** [comment]
I know it's a false postiv message.
You can ignore it, SAK is 100% clean.
See here similary post -> https://github.com/dezem/SAK/issues/2

And check for other virus tools here -> https://www.virustotal.com/gui/file/bf85918e98a65fd9e6a4fa3c677181cd1d652506665d4017a32b7501d47ef092/detection

**Comment by Bonethugs1980** [comment]
Thanks, I did see the other post #2.  But because it saw it as a trojan, then saw this as the nymeria - nearly freakout!  Bitdefender does tend to have it's 'max' settings on for protection.

Thanks for reposting.

Cheers :)
