### ISSUE TITLE
Firmware 15 forwarder not working

### ISSUE THREAD

**Issue by FabiV7** [dezem/SAK#47]
With firmware 15 the created forwarders not gonna work. 

New prod.keys with a compatible lockpik.rcm where taken

**Comment by dezem** [comment]
If the forwarder don't work on fw15.0.
Your missing the right sigpatches.

There are no changes needed for fw15.X versus fw14.X.

If you get a never ending loading wheel, then you have a problem with your icon.

**Comment by FabiV7** [comment]
It was the icon size 
All sorted and works great
