### ISSUE TITLE
windows 10 detects the .7zip as a virus

### ISSUE THREAD

**Issue by Djam808** [dezem/SAK#9]
I did see other posts relating to this but I'm new and they are old so I'm bringing this up again. When I download any version of this and try to extract or open the 7,zip folder, Windows pops up with a message saying its a virus or potential unwanted program. and then it disappears. tried downloading it 3 times same issue.

**Comment by dezem** [comment]
Hi,
take a look, what i already said in the other issue post 😉 

https://github.com/dezem/SAK/issues/7#issuecomment-650735487
